### ISSUE TITLE
Video playback issue

### ISSUE THREAD

**Issue by msahad** [JackyAndroid/AndroidChromium#29]
Some youtube video doesn't play in mobile view(m.youtube.com) . It says "your browser does not currently recognize any of the video formats available". If we request desktop site, video play in youtube desktop version. When we check in  youtube.com/html5   its shows H.264 and MSE & H.264 doesn't support by this browser. It works fine in chromium 48.0.2 version. 

Sample video link  https://www.youtube.com/watch?v=qbXXVBfuU24

**Comment by JackyAndroid** [comment]
Is to solve the problem

**Comment by AviFix** [comment]
Hi,

I think i have the same problem.
[Link to a video that isn't working](https://www.hidabroot.org/video/210186)

Tanks
Avi

**Comment by AviFix** [comment]
Hi,

Adding these parameters in the build command (in the original chromium project) adds h264/aac support, and solves the problem.

`gn gen --args='target_os="android" proprietary_codecs=true ffmpeg_branding="Chrome"' out/Default
`
But i don't know how to integrate it in this project.

Any ideas on how to integrate it in this project?

Thanks

**Comment by JackyAndroid** [comment]
@AviFix After the kernel has been compiled, it can be integrated into the project in accordance with the README steps

**Comment by AviFix** [comment]
@JackyAndroid  There are a lot of files in the src/out folder (About 30GB).
Could you please direct me to the files i need to change in the project for getting the h264 support?

Thanks
Avi

**Comment by JackyAndroid** [comment]
@AviFix 
### The upgrade Chromium kernel steps are as follows
---

### Preparation

Refer to [official](https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md) and other tutorial compile chromium source code, and can generate chrome apk

### purpose

Using AndroidStudio debugging Chromium Android

### The build process

1.	Android Studio as a development environment, from Chromium for Android from chrome module source code, to join the Android project.
2.	Native code in the chromium environment to build, as so file to join the Android project
3.	Basic module (base, the content, net, etc.) in the chromium environment to build into a jar package, then add to the Android project
4.	content, chrome, UI modules such as resource file to join an Android library project

### Why can't a resource file are directly added to the Android project?

Because namespace problems, such as the content of the module resources namespace is org.chromium.content,the chrome module namespace is org.chromium.chrome, so need to build different Android library project, specify different package name.

### Directory corresponding relation

app/libs ----------- chromium/src/out/gnbuild/lib.java

app/src/main/aidl ----------- chromium/src/chrome/android/java/src/android/support/customtabs/*.aidl

app/src/main/assets ----------- chromium/src/out/gnbuild/

app/src/main/java ------------ chromium/src/chrome/android/java/src

app/src/main/jniLibs ----------- chromium/src/out/gnbuild/

app/src/main/res（app module init res）

libraries/androidmedia_res ----------- chromium/src/third_party/android_media/java/res

libraries/chrome_res ----------- chromium/src/chrome/android/java/res & chromium/src/chrome/android/java/res_chromium

libraries/content_res ----------- chromium/src/content/public/android/java/res

libraries/datausagechart_res --------- chromium/src/third_party/android_data_chart/java/res

libraries/ui_res ---------- chromium/src/ui/android/java/res

### The kernel upgrade matters needing attention

1.	Pak and dat files need to be added to the assets directory, and cannot be compressed
2.	Aidl files added to the main/aidl
3. The current build chromium version is 55.0.2883.99
4. Because some Java file is through the C compiler generated, there is the chromium/src/out directory or exist in the jars.If according to corresponding relation between the above updated version missing files, please go to the out/directory search, add corresponding files according to the namespace.There are some temporary generated XML resource file also need the out/directory on copy to the corresponding resource module.

**Comment by AviFix** [comment]
Hi,

I'm not sure i understand what to do.

Is it possible you will find the time to do it? (rebuild the chrome with h264 support and add it to this project).

Thanks a lot
Avi

**Comment by JackyAndroid** [comment]
The latest version has to fix the problem
